export const data = [
  {
    id: 1,
    name: "Background",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 2,
    name: "Skin",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 3,
    name: "Tats",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 4,
    name: "Eyes",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 5,
    name: "Mouth",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 6,
    name: "Clothes",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 7,
    name: "Eyeware",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 8,
    name: "Jewerly",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 9,
    name: "Headware",
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
];
