import BackgroundImg from "../../public/images/gallery/image 24 (1).png";
import SkinImg from "../../public/images/gallery/image 24.png";
import TatsImg from "../../public/images/gallery/image 25.png";
import EyesImg from "../../public/images/gallery/image 26.png";
import MouthImg from "../../public/images/gallery/image 27.png";
import ClothesImg from "../../public/images/gallery/image 28.png";
import EyewareImg from "../../public/images/gallery/image 30.png";
import JewerlyImg from "../../public/images/gallery/image 31.png";
import HeadwareImg from "../../public/images/gallery/image 32.png";

export const data = [
  {
    id: 1,
    name: "Background",
    imgLeft: true,
    image: '/images/gallery/image 24.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 2,
    name: "Skin",
    image: '/images/gallery/image 24 (1).png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 3,
    name: "Tats",
    image: '/images/gallery/image 25.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 4,
    name: "Eyes",
    image: '/images/gallery/image 26.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",

    ],
  },
  {
    id: 5,
    name: "Mouth",
    image: '/images/gallery/image 27.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 6,
    name: "Clothes",
    image: '/images/gallery/image 28.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 7,
    name: "Eyeware",
    image: '/images/gallery/image 30.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 8,
    name: "Jewerly",
    image: '/images/gallery/image 31.png',
      options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 9,
    name: "Headware",
    image: '/images/gallery/image 32.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
];
