
export const data = [
  {
    id: 1,
    name: "Background",
    imgLeft: true,
    image: '/images/gallery/image 24.png',
    options: [
      "Grey",
      "Cream",
      "Grey",
      "Cool Grey",
      "Midnight",
      "Emerald",
      "Morado",
      "Coral",
      "Yellow",
      "Light Grey",
    ],
  },
  {
    id: 2,
    name: "Skin",
    image: '/images/gallery/image 24 (1).png',
    options: [
      "Yellow",
      "Albino",
      "Transparent",
      "Textured Grey",
      "Tesla Bot",
      "Emerald",
      "Spider Martian",
      "Sand",
      "Red",
      "Radioactive",
      "Purple",
      "Pink",
      "Miles Martian",
      "Iridescent",
      "Hell Spawn",
      "Grey",
      "Green",
      "Decaying",
      "Deadly Pool",
      "Dark Grey",
      "Black",
      "Blue"
    ],
  },
  {
    id: 3,
    name: "Facial Features",
    image: '/images/gallery/image 25.png',
    options: [
      "None",
      "Sagittal Crest",
      "Scars ",
      "Stiches",
      "Bandaids",
    ],
  },
  {
    id: 4,
    name: "Eyes",
    image: '/images/gallery/image 26.png',
    options: [
      "Black Peeled Open",
      "Black",
      "Blue Angry",
      "Blue Bored",
      "Blue Not Impressed",
      "Blue",
      "Cyclops primitive",
      "Cyclops",
      "Dark Green Angry",
      "Dark Green Bored",
      "Dark Green Not Impressed",
      "Dark Green",
      "Green Angry",
      "Green Bored",
      "Green Peeled Open",
      "Green",
      "Heterochromia Iridis",
      "Hypnotitzed",
      "laser beams green",
      "Laser Beams pink",
      "Purple Angry",
      "Purple Bored",
      "Purple Not Impressed",
      "Purple",
      "Radioactive",
      "Red Angry",
      "Red Bored",
      "Red Not Impressed",
      "Red",
      "Sectoral Heterochromia",
      "Sewn Shut",
      "The Fly",
      "Thirt Eye Open",
      "White",
      "Angry Hypnotiezd",
      "Manic",
      "Pink",
      "Green Not Intersted"
    ],
  },
  {
    id: 5,
    name: "Mouth",
    image: '/images/gallery/image 27.png',
    options: [
      "Angry",
      "Bandana ",
      "Black Mask ",
      "Bubblegum",
      "Corn Cob Pipe",
      "Dagger In The Mouth",
      "Decaying",
      "Fu Manchu",
      "Grass Straw",
      "Joint ",
      "Joint Lit",
      "Joint Lit",
      "Mars Martian",
      "Passive",
      "Pipe",
      "Predator",
      "Radioactive",
      "Respirator",
      "Sewn Shut",
      "Stubble With Dagger",
      "Stubble With Joint",
      "Stubble",
      "Toothpick",
      "Vampire",
      "Xenomorph",
      "Yuck Mouth",
      "Stubble with Pipe",
      "Stubble with corn pipe",
      "Cigar 0",
      "Stubble with Straw",
      "Stubble Toothpick",
      "Shadow Radioactive",
      "Stubbs ciggar",
      "Spagethi ",
      "Radioactjve wugh dagger ",
      "Facehugger",
      "Shadow"
    ],
  },
  {
    id: 6,
    name: "Clothes",
    image: '/images/gallery/image 28.png',
    options: [
      "Adventurer",
      "Army",
      "Boxer Female",
      "Boxer Male",
      "Button Up Black",
      "Button Up Galaxy",
      "Button Up Hawaiian",
      "Button Up NghtOwl",
      "Button Up Purple",
      "Button Up Striped",
      "Button Up White",
      "Uniform",
      "Cape Black Knight",
      "Cape Hell Spawn",
      "Coogie Sweater",
      "Gi",
      "Hoodie AOTA",
      "Hoodie Clay",
      "Bomber Jacket",
      "Hip Hop Jacket",
      "Leather Jacket & Hoodie",
      "Biker Jacket",
      "Leather Jacket Red",
      "Leather Jacket Tan",
      "Mercenary",
      "Military Shemagh",
      "None Female",
      "None Male",
      "Blue Plaid",
      "Dark Green Plaid",
      "Sailor",
      "Shirt Black",
      "Shirt Ripped",
      "Shirt Tie Dye",
      "Space Suit Female",
      "Space Suit Male",
      "Tank Artist",
      "Tank Green Thumb",
      "Toga",
      "Trailblazer Blue Shirt",
      "Trailblazer Ripped Shirt",
      "Trailblazer Tan Shirt",
      "Bullet Proof vest",
      "Construction",
      "Fisherman",
      "Tank Grey",
      "Tank white ",
      "Spacesuit Male Blue",
      "Spacesuit Male Grey",
      "Spacesuit Female Magenta",
      "Spacesuit Female Purple ",
      "Martian Spaceman",
      "Prison Jumpsuit",
      "Buddist Monk",
      "Lab coat",
      "Purple tank",
      "Trainer",
    ],
  },
  {
    id: 7,
    name: "Eyewear",
    image: '/images/gallery/image 30.png',
    options: [
      "AR Glasses",
      "Wayfarers",
      "Aviators Blue",
      "Aviators Green",
      "Aviators Orange",
      "Reading Glasses",
      "Eye Patch",
      "Perry's",
      "Monicle",
      "None",
      "AOTA Stunnas",
      "Windsors",
    ],
  },
  {
    id: 8,
    name: "Jewelry",
    image: '/images/gallery/image 31.png',
      options: [
      "Gold Cross & Piercings",
      "Silver Eye Chain",
      "Black Piercings ",
      "Cross & Nose Ring",
      "Gold Piercing",
      "All Gold",
      "Silver & Black Rings",
      "Black Piercings & Nose Rings",
      "All Black",
      "Bling Bling",
      "Diamond Ear Ring",
      "Black Ear Ring",
      "Black Ankh ",
      "Gold Ankh ",
      "Silver Ankh ",
      "Black Cross",
      "Diamond Ankh ",
      "Gold Cross",
      "Silver Cross",
      "Gold Ear Ring ",
      "Silver Ear Ring",
      "None",
      "Nose Diamond Stud",
      "Apocalypto",
      "Jaguar Teeth",
      "Claw",
      "Raptor Teeth",
      "Claw & Raptor Teeth",
      "Tribal Paint & Claw",
      "Shark Tooth Ear Ring",
      "Black Alien",
      "Gold Alien",
      "Silver Alien",
      "Gothic",
      "Diamond Alien",
    ],
  },
  {
    id: 9,
    name: "Headware",
    image: '/images/gallery/image 32.png',
    options: [
      "Hat AOTA",
      "Bandages",
      "Bandana With Joint",
      "Bandana Blue",
      "Bandana Red",
      "Bandana Green",
      "Bandana White",
      "Hat Blue",
      "Bohemian Hat",
      "Brain Exposed",
      "Fisherman",
      "Carmen Miranda Hat",
      "Conscience",
      "Cowboy Hat",
      "Flower Headress",
      "Fro ",
      "Halo",
      "Headphones",
      "Horns",
      "Incubator & Conscience",
      "Incubator",
      "Kyle Hat",
      "Hat Motivv",
      "None",
      "Pilot",
      "Pods",
      "Sailor ",
      "Hat Secret Stash",
      "Stitched Scalp & Halo",
      "Stiched Scalp",
      "Sushi Chef",
      "Zorg",
      "Neon Blue Mohawk ",
      "Neon Pink Mohawk ",
      "AOTA Beanie Black",
      "Neon Green Mohawk ",
      "Martinez & Co Hat",
      "Bucket Hat Green",
      "Bucket Hat Red Pins",
      "Pink Wig",
      "AOTA Hat Backwards Tan",
      "Visor",
      "AOTA Hat Blue",
      "MF Doom Mask",
      "Ski Mask",
      "Moped",
      "Panty Hose ",
    ],
  },
  {
    id: 10,
    name: "Head TT",
    image: '/images/gallery/image 32.png',
    options: [
      "Alien Abduction",
      "Alien Flourish",
      "Angelic Dove",
      "Aota Atttacks",
      "Aota Bull",
      "Aota Old English",
      "Aota Teardrops",
      "Aota Script",
      "Tagger",
      "Bomb",
      "Bouquet Of Shrooms",
      "Bull Skull",
      "Candy Alien",
      "Chakras",
      "Cow Abduction",
      "Crow Flying",
      "Crystal Skull",
      "Dragon Selfie",
      "Slivering",
      "Dragon",
      "Eagle Face",
      "Flourish",
      "Ganesha",
      "Green Dragon",
      "Hasma Hand",
      "Snake Skeleton",
      "Japanesse Dragon",
      "Ninja Spiral",
      "Ouroboros Dragon",
      "Phoenix Wing",
      "Phoenix",
      "Pigeon & Stars",
      "Pink Flourish",
      "Pirate Flag",
      "Pirate Ship",
      "Ray Gun",
      "Plants",
      "Script Floursih",
      "Serpant",
      "Shark & Cross",
      "Simple Bird Script",
      "Small Dove ",
      "Solar System",
      "Space Minamlist",
      "Spiritual",
      "Tribal Lizard",
      "Third Eye",
      "Tribal",
      "Viper Strike",
      "Snake Attack",
      "Woman & Roses",
      "None"
     
    ],
  },
  {
    id: 11,
    name: "Neck Tat",
    image: '/images/gallery/image 32.png',
    options: [
      "Abstract Art",
      "Black Widow",
      "Blast Off",
      "Decaying Finger",
      "Flock Of Birds",
      "Floral Om",
      "Interwinderd Snake",
      "Lizard Crawling",
      "Lotus Flower",
      "Mushroom Sleeve",
      "Owl Neck",
      "Pirate Key",
      "Pirate Sword",
      "Praying Hands",
      "Rose",
      "Shrooms Growing",
      "Spiders Crawling",
      "Sugar Skull",
      "Tallies & Love",
      "None",
      "AOTA Symbol",
      "Cross & Rosary",
      "Daggers & Rabbit",
     
    ],
  },
  {
    id: 12,
    name: "Body Tat",
    image: '/images/gallery/image 32.png',
    options: [
      "Aliens On The Ave",
      "Bones",
      "Dagger ",
      "Diamond",
      "Doll",
      "Dragons",
      "Dream Script",
      "Eagle Wings",
      "Ganesha",
      "Green Thumb",
      "Guardian Eagles ",
      "Hibiscus & Tribal Sleeve",
      "Liberty Or Death",
      "Milky Way",
      "Nautical Mermaid",
      "Not Even One Letter",
      "Orchids ",
      "Phoenix Chest",
      "Pirate Ship",
      "None",
      "Prestigious Samauri",
      "Skater",
      "Skelton Chest",
      "Space Station",
      "Spanish Lizard",
      "The Beast",
      "The Rock",
      "UFO Minimalist ",
      "Wise Owl",
      "Wolf",
      "Tribal Bull",
      "Tribal Heart",
      "Tribal Warrior",
    ],
  },
];
